name: pull request
on:
  pull_request:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'main'

jobs:
  lint:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: Atlas-SMR-Execution
      - uses: ./Atlas-SMR-Execution/.github/actions/checkout-dependencies
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2025-06-09
          components: rustfmt, clippy
      - name: Check versions
        working-directory: Atlas-SMR-Execution
        run: |
          rustup --version
          rustup show
          cargo --version
          cargo fmt --version
          cargo clippy --version
      - name: Lint formatting
        working-directory: Atlas-SMR-Execution
        run: cargo fmt --all -- --check
      - name: Lint code
        working-directory: Atlas-SMR-Execution
        run: cargo clippy --all-targets --no-deps -- -D warnings

  unit-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      # Shrink artifact size by not including debug info. Makes build faster and shrinks cache.
      CARGO_PROFILE_DEV_DEBUG: 0
      CARGO_PROFILE_TEST_DEBUG: 0
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v3
        with:
          path: Atlas-SMR-Execution
      - uses: ./Atlas-SMR-Execution/.github/actions/checkout-dependencies
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2025-06-09
      - uses: taiki-e/install-action@nextest
      - run: cargo build --tests
        working-directory: Atlas-SMR-Execution
      - run: cargo nextest run --no-tests pass
        working-directory: Atlas-SMR-Execution
